#!/usr/bin/env python

#simple python script to send remote IR commands to a TiVo DVR
#this script should never be called directly, but rather via
#symbolic links to it
#
#Written by Charlie Meyer <charlie@charliemeyer.net>
#December 2012

import socket
import sys
import time
import os.path

#set this to the ip address of the tivo to control
tivo_address = "192.168.1.6"

sock = None

def connect():
    global sock
    global tivo_address
    try:
        sock = socket.socket()
        sock.settimeout(5)
        sock.connect((tivo_address, 31339))
        sock.settimeout(None)
    except Exception, msg:
        print msg

def disconnect():
    global sock
    sock.close()

def send_code(code):
    if not sock:
        connect()
    try:
        sock.sendall("IRCODE "+code+"\r")
        time.sleep(0.1)
    except Exception, msg:
        print msg

times = 1;
if(len(sys.argv) > 1):
    times = int(sys.argv[1])

for i in range(0,times):
    send_code(os.path.basename(sys.argv[0]))

disconnect()
